apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  selector:
    matchLabels:
      app: myapp
  replicas: 3
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "100m" # 100m CPU cores
            memory: "256Mi" # 256 Mebibytes (MiB)
          requests:
            cpu: "50m" # 50m CPU cores
            memory: "128Mi" # 128 Mebibytes (MiB)
